wandb_version: 1

policy:
  desc: null
  value: MlpPolicy
total_timesteps:
  desc: null
  value: 30000
_wandb:
  desc: null
  value:
    code_path: code/firstur.py
    python_version: 3.11.4
    cli_version: 0.15.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1689442583.559032
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 1
      - 2
      - 3
      - 16
      - 22
      - 23
      - 35
      4: 3.11.4
      5: 0.15.5
      8:
      - 5
algo:
  desc: null
  value: PPO
policy_class:
  desc: null
  value: <class 'stable_baselines3.common.policies.ActorCriticPolicy'>
device:
  desc: null
  value: cpu
verbose:
  desc: null
  value: 1
policy_kwargs:
  desc: null
  value: '{}'
num_timesteps:
  desc: null
  value: 0
_total_timesteps:
  desc: null
  value: 30000
_num_timesteps_at_start:
  desc: null
  value: 0
seed:
  desc: null
  value: None
action_noise:
  desc: null
  value: None
start_time:
  desc: null
  value: 1689442584170400000
learning_rate:
  desc: null
  value: 0.0003
tensorboard_log:
  desc: null
  value: runs/pponew
_last_obs:
  desc: null
  value: "[[[ 0  0  7  7]\n  [ 1  0  0  0]\n  [ 2  0  0  0]\n  [ 3  0  0  0]\n  [\
    \ 4  1  0  0]\n  [ 5  0  0  0]\n  [ 6  0  0  0]\n  [ 7  0  0  0]\n  [ 8  1  0\
    \  0]\n  [ 9  0  0  0]\n  [10  0  0  0]\n  [11  0  0  0]\n  [12  0  0  0]\n  [13\
    \  0  0  0]\n  [14  1  0  0]\n  [15  0  0  0]\n  [ 0  0  0  0]]]"
_last_episode_starts:
  desc: null
  value: '[ True]'
_last_original_obs:
  desc: null
  value: None
_episode_num:
  desc: null
  value: 0
use_sde:
  desc: null
  value: 'False'
sde_sample_freq:
  desc: null
  value: -1
_current_progress_remaining:
  desc: null
  value: 1.0
_stats_window_size:
  desc: null
  value: 100
ep_info_buffer:
  desc: null
  value: deque([], maxlen=100)
ep_success_buffer:
  desc: null
  value: deque([], maxlen=100)
_n_updates:
  desc: null
  value: 0
_custom_logger:
  desc: null
  value: 'False'
env:
  desc: null
  value: <stable_baselines3.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x7f251391fdd0>
_vec_normalize_env:
  desc: null
  value: None
observation_space:
  desc: null
  value: Box(-100, 100, (17, 4), int8)
action_space:
  desc: null
  value: Discrete(7)
n_envs:
  desc: null
  value: 1
n_steps:
  desc: null
  value: 2048
gamma:
  desc: null
  value: 0.99
gae_lambda:
  desc: null
  value: 0.95
ent_coef:
  desc: null
  value: 0.0
vf_coef:
  desc: null
  value: 0.5
max_grad_norm:
  desc: null
  value: 0.5
batch_size:
  desc: null
  value: 64
n_epochs:
  desc: null
  value: 10
clip_range:
  desc: null
  value: <function constant_fn.<locals>.func at 0x7f25ae7a6520>
clip_range_vf:
  desc: null
  value: None
normalize_advantage:
  desc: null
  value: 'True'
target_kl:
  desc: null
  value: None
lr_schedule:
  desc: null
  value: <function constant_fn.<locals>.func at 0x7f25ae7a56c0>
rollout_buffer:
  desc: null
  value: <stable_baselines3.common.buffers.RolloutBuffer object at 0x7f25175c6710>
_logger:
  desc: null
  value: <stable_baselines3.common.logger.Logger object at 0x7f25138e1450>
